# Generated by Django 3.2.7 on 2021-10-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_person_species'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=350)),
                ('description_large', models.TextField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
