# Generated by Django 3.2.7 on 2021-10-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=200)),
                ('choice', models.CharField(max_length=200)),
                ('themessage', models.TextField(max_length=100)),
            ],
        ),
    ]
