# Generated by Django 3.2.7 on 2021-10-07 22:41

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_text', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to=core.models.upload_to)),
            ],
        ),
    ]
