# Generated by Django 3.2.7 on 2021-10-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_articles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ('-published',)},
        ),
        migrations.AddField(
            model_name='articles',
            name='isFeatured',
            field=models.BooleanField(default=True),
        ),
    ]
